version: '3.8'
services:
  postgres:
    container_name: miro-like-app-demo-postgres
    image: postgres:15.2-alpine
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
